config/routes.rb
Rails.application.routes.draw do

  root 'pets#index'

  delete 'pets/:id/destroy' => 'pets#destroy', as: :delete
  get 'pets/:id/clone' => 'pets#clone', as: :clone
  resources :pets

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	CATEGORIES = ['Dog', 'Cat', 'Elephant', 'Unicorn', 'Pokemon']
	validates :name, presence: true
	validates :category, inclusion: {in: CATEGORIES}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
	def index
		@pets = Pet.all
	end

	def show
		@pet = Pet.find(params[:id])
	end

	def new
		@pet = Pet.new
	end

	def create
		@pet = Pet.create(pets_params)
		redirect_to root_path
	end

	def destroy
		@pet = Pet.find(params[:id])
		@pet.destroy
		redirect_to root_path
	end

	def clone
		@pet = Pet.find(params[:id])
		@clone_pet = @pet.dup
		@clone_pet.save
		redirect_to root_path
	end


	private

	def pets_params
		params.require(:pet).permit(:name, :address, :category, :found_on)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lostkitty</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/index.html.erb
<div class="text-center">
<h1><%= link_to "Have you found a pet? Add it!", new_pet_path %></h1>
<div class="container">
	<div class="row">
		<% @pets.each do |p|%>
			<div class="col-xs-12 col-sm-6 col-md-4">
				<div class="card">
					<p><%= link_to p.name, pet_path(p) %></p>
					<p><%= p.address %></p>
					<p><%= p.category %></p>
					<p><%= p.found_on %></p>
					<p><%= link_to "Kill IT!", pet_path(p), method: :delete %></p>
					<p><%= link_to 'Clone me baby!', clone_path(p) %></p>
				</div>
			</div>
		 <% end %>
 	</div>
</div>
</div>

app/views/pets/new.html.erb
<%= form_for @pet do |f| %>
	<%= f.text_field :name %>
	<%= f.text_field :address %>
	<%= f.select :category, Pet::CATEGORIES, prompt: "Categories" %>
	<%= f.date_field :found_on %>
	<%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h2><%= @pet.address %></h2>
<h2><%= @pet.category %></h2>
<h2><%= @pet.found_on %></h2>
<%= link_to 'Full list of pets', pets_path %>